-- Step 1: Rename receptionists to receptionist_catalog
ALTER TABLE public.receptionists RENAME TO receptionist_catalog;

-- Step 2: Create hired_receptionists table
CREATE TABLE public.hired_receptionists (
  id bigint generated by default as identity primary key,
  catalog_id bigint references public.receptionist_catalog(id),
  full_name text,
  description text,
  stereotype text,
  avatar text,
  traits jsonb,
  voice text,
  age numeric,
  first_name text,
  elevenlabs_agent_id text,
  elevenlabs_voice_id text,
  call_types text DEFAULT 'none' CHECK (call_types IN ('none', 'inbound', 'outbound', 'both')),
  phone_number text,
  is_active boolean DEFAULT false,
  model text,
  compliments float4 DEFAULT 0,
  complaints float4 DEFAULT 0,
  hierarchy_level int DEFAULT 2,
  reports_to text,
  status text DEFAULT 'idle',
  current_activity text,
  memory_items int DEFAULT 0,
  tasks_done int DEFAULT 0,
  hired_at timestamptz DEFAULT now()
);
