import React, {useEffect,useState} from 'react';
import {ArrowLeft,ChevronRight,Plus,RotateCcw,Settings2,X} from 'lucide-react';
import {ancestry,descendants,ordered} from '../../sonar/lib/dropInGraph';
import {useDropInConcept} from './DropInConceptContext';
import {previewGraph,STATUS_LABELS,STATUSES} from './dropInConceptModel';
import './drop-in-concepts.css';

export function DropInStatusBar(){
  const {status,setStatus,undo,canUndo,add,storageError}=useDropInConcept();
  return <div className="dc-context"><div className="dc-status-tabs" role="tablist" aria-label="Appointment status">{STATUSES.map(value=><button role="tab" aria-selected={status===value} key={value} onClick={()=>setStatus(value)}><i/>{STATUS_LABELS[value]}</button>)}</div><div className="dc-context-actions"><span>{storageError?'Session draft':'Local draft'}</span><button aria-label="Undo Drop In change" title="Undo" disabled={!canUndo} onClick={undo}><RotateCcw size={14}/></button><button onClick={()=>add('collection','New drop-in')}><Plus size={14}/>Drop-in</button></div></div>;
}
export function DropInTools(){
  const api=useDropInConcept();const {items,status,selected,select,edit,move,remove,error,setError}=api;
  const [panel,setPanel]=useState(null);const [draft,setDraft]=useState(null);const [previewPath,setPreviewPath]=useState([]);const [previewAction,setPreviewAction]=useState(null);
  useEffect(()=>{setDraft(selected?{name:selected.name,purpose:selected.purpose,prompt:selected.prompt,is_active:selected.is_active,parent_id:selected.parent_id}:null);},[selected]);
  useEffect(()=>{setPanel(null);setPreviewPath([]);setPreviewAction(null);},[status]);
  useEffect(()=>{if(!panel)return;const close=e=>{if(e.key==='Escape')setPanel(null);};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[panel]);
  const rows=items.filter(n=>n.available_on_status===status).sort(ordered);
  const visible=previewGraph(rows);const allowed=selected?new Set([selected.id,...descendants(items,selected.id)]):new Set();
  const parent=selected&&items.find(n=>n.id===selected.parent_id);
  const blocked=selected&&ancestry(items,selected.id).some(id=>!items.find(n=>n.id===id)?.is_active);
  const usablePath=previewPath.filter(id=>visible.some(n=>n.id===id));const currentParent=usablePath.at(-1)||null;
  const choices=visible.filter(n=>(n.parent_id||null)===currentParent);
  const update=(field,value)=>setDraft({...draft,[field]:value});
  return <><div className="dc-selection-dock"><div><span className="cl-caption">{selected?'SELECTED DROP-IN':`${STATUS_LABELS[status].toUpperCase()} APPOINTMENT`}</span><strong>{selected?.name||`${rows.filter(n=>!n.parent_id).length} starting choices`}</strong><span>{selected?(parent?`After ${parent.name}`:'At the appointment level'):'Select an action to edit its purpose and instructions.'}</span></div><div>{selected&&<><span className={`dc-state ${!selected.is_active||blocked?'off':''}`}>{!selected.is_active?'Disabled':blocked?'Hidden by parent':'Available'}</span><button onClick={()=>setPanel(panel==='edit'?null:'edit')}><Settings2 size={14}/>Edit action</button></>}<button onClick={()=>{setPanel(panel==='preview'?null:'preview');setPreviewPath([]);setPreviewAction(null);}}>Preview choices<ChevronRight size={13}/></button></div></div>
    {error&&<div className="dc-error" role="alert">{error}<button aria-label="Dismiss error" onClick={()=>setError('')}><X size={13}/></button></div>}
    {panel&&<aside className="dc-inspector" aria-label={panel==='edit'?'Edit Drop In':'Appointment choice preview'}><header><div><span className="cl-caption">{panel==='edit'?'DROP-IN DETAILS':'APPOINTMENT PREVIEW'}</span><h2>{panel==='edit'?'Make it useful.':`${STATUS_LABELS[status]} appointment`}</h2></div><button aria-label="Close inspector" onClick={()=>setPanel(null)}><X size={17}/></button></header>
      {panel==='edit'&&selected&&draft?<form onSubmit={e=>{e.preventDefault();if(edit(selected.id,draft))setPanel(null);}}><label>Name<input aria-label="Drop In name" maxLength={64} required value={draft.name} onChange={e=>update('name',e.target.value)}/></label><label>Purpose<span>What should the receptionist call about?</span><input aria-label="Drop In purpose" maxLength={30} required value={draft.purpose} onChange={e=>update('purpose',e.target.value)}/><small>{draft.purpose.length}/30</small></label><label>Instructions<textarea aria-label="Drop In instructions" rows={7} maxLength={6000} required value={draft.prompt} onChange={e=>update('prompt',e.target.value)}/></label><label className="dc-enabled"><input type="checkbox" checked={draft.is_active} onChange={e=>update('is_active',e.target.checked)}/>Enabled</label><label>Appears after<select aria-label="Drop In parent" value={draft.parent_id||''} onChange={e=>update('parent_id',e.target.value||null)}><option value="">Appointment level</option>{rows.filter(n=>!allowed.has(n.id)).map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select></label><div className="dc-editor-actions"><button type="button" onClick={()=>{remove(selected.id);setPanel(null);}}>Remove action</button><button type="submit" className="dc-apply">Apply to draft</button></div><p className="dc-local-note">Shared by all fifteen concepts. Saved on this browser; no live Drop Ins are changed.</p></form>:panel==='edit'?<p>Select a Drop In in the builder.</p>:<div className="dc-appointment-preview"><span className="dc-preview-status"><i/>{STATUS_LABELS[status]}</span><p>Choose what happens next.</p>{(currentParent||previewAction)&&<button className="dc-preview-back" onClick={()=>{if(previewAction)setPreviewAction(null);else setPreviewPath(usablePath.slice(0,-1));}}><ArrowLeft size={13}/>{previewAction?'Back to choices':'Back'}</button>}{previewAction&&visible.some(n=>n.id===previewAction.id)?<div className="dc-call-preview"><span className="cl-caption">SELECTED ACTION</span><h3>{items.find(n=>n.id===previewAction.id)?.name}</h3><p>Call the customer to {items.find(n=>n.id===previewAction.id)?.purpose.toLowerCase()}?</p><button type="button" disabled>Preview only · no call placed</button></div>:<><h3>{rows.find(n=>n.id===currentParent)?.name||'Available Drop Ins'}</h3><div className="dc-preview-choices">{choices.map(n=><button key={n.id} onClick={()=>{select(n.id);if(n.has_children)setPreviewPath([...usablePath,n.id]);else setPreviewAction(n);}}>{n.name}<ChevronRight size={14}/></button>)}{!choices.length&&<p>No enabled choices at this level.</p>}</div></>}<p className="dc-local-note">A parent reveals its children. Disabled actions and branches beneath disabled parents are hidden.</p></div>}
    </aside>}
  </>;
}
