create table if not exists public.created_receptionists (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  business_id bigint,
  status text not null default 'draft' check (status in ('draft', 'generating', 'ready', 'converted', 'abandoned')),
  full_name text,
  first_name text,
  gender text,
  age text,
  description text,
  traits jsonb not null default '[]'::jsonb,
  voice_id text,
  voice_name text,
  voice_description text,
  portrait_options jsonb not null default '[]'::jsonb,
  selected_portrait_id text,
  selected_portrait_url text,
  hired_receptionist_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  converted_at timestamptz
);

create index if not exists created_receptionists_user_id_idx on public.created_receptionists (user_id);
create index if not exists created_receptionists_business_id_idx on public.created_receptionists (business_id);
create index if not exists created_receptionists_status_idx on public.created_receptionists (user_id, status);

alter table public.created_receptionists enable row level security;

drop policy if exists "Users can view their created receptionists" on public.created_receptionists;
create policy "Users can view their created receptionists" on public.created_receptionists
  for select using (auth.uid() = user_id);

drop policy if exists "Users can create their created receptionists" on public.created_receptionists;
create policy "Users can create their created receptionists" on public.created_receptionists
  for insert with check (auth.uid() = user_id);

drop policy if exists "Users can update their created receptionists" on public.created_receptionists;
create policy "Users can update their created receptionists" on public.created_receptionists
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Users can delete their created receptionists" on public.created_receptionists;
create policy "Users can delete their created receptionists" on public.created_receptionists
  for delete using (auth.uid() = user_id);
